version: '3.8'

# Intra docker communication
networks:
  app_network:
    driver: bridge

services:
  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    hostname: consumer-service  # Explicit hostname
    ports:
      - "5000:5000"
    volumes:
      - ./templates:/app/templates
    networks:
      - app_network

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    hostname: producer-service
    volumes:
      - ./ip_addresses.csv:/app/ip_addresses.csv
    networks:
      - app_network
    depends_on:
      - consumer

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./templates:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
    depends_on:
      - consumer